apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: moviestore
spec:
  dnsNames:
    - aksmoviestore.francecentral.cloudapp.azure.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: letsencrypt